name: 'Cascade merge'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'Token'
    required: true
    default: ''
  branch:
    description: 'Current branch'
    required: true
    default: ''
  repo:
    description: 'Current repo'
    required: true
    default: ''
  owner:
    description: 'Owner repo'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'